image: php:7.4.19-fpm-buster

pipelines:
  default:
    - step:
        caches:
          - node
          - composer
        script:
          - apt-get update && apt-get install -qy git zip curl default-mysql-client
          - docker-php-ext-install pdo_mysql
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh
          - bash nodesource_setup.sh
          - apt-get install -qy nodejs
          - node -v
          - composer install
          - npm install
          # - npm lint
          - npm run prod
          - npm run compress
          - ln -f -s .env.pipelines .env
          - php artisan migrate --force --seed
          # - php artisan install
          - php artisan serve &
          - sleep 5
          #- ./vendor/bin/phpunit
          - curl -vk http://localhost:8000
        services:
          - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
